### PR TITLE
Rebuild for python310

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by beckermr** [comment]
Maybe we need to install from the git source and not sdist?

**Comment by mwcraig** [comment]
I'm hoping this is fixed now -- it does build locally for me. Turns out you need to explicitly tell cython to make C++ files if that is what you want.

**Comment by mwcraig** [comment]
Summary of affairs currently:

+ Python `3.10` builds are failing on all platforms with an error [like this](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=516136&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&l=902)
+ All Windows builds are failing because `$(find . -name \*.pyx)` doesn't work on Windows.
+ All of the OSX ARM builds are failing when cython tries to run, see, e.g., [this log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=516136&view=logs&j=1b8be447-c2bd-5772-b66a-a1146441bf88&t=0da7bde9-21e8-5d19-f418-738876121ca7&l=302)
    - `halotools` builds without error on my M1 Mac with python 3.10 and numpy 1.21, which makes the failures here particularly confusing to me

**Comment by beckermr** [comment]
Maybe pip has some magic that will help?

**Comment by beckermr** [comment]
Well I give up.

**Pull request closed without merging**
