### PR TITLE
ENH: add osx arm

### LINKED ISSUE #13: @conda-forge-admin rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #13.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #13

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@aphearin You can get a new mac now. ;p

**Comment by beckermr** [comment]
@mwcraig This one is ready to go! I hope we can merge before the end of the day!

**Comment by mwcraig** [comment]
Thanks, will merge this and come back to #12 later today or tomorrow.

**Pull request merged**
